### ISSUE TITLE
`MOIU._single_variable_flag`

### ISSUE THREAD

**Issue by pedromxavier** [jump-dev/MathOptInterface.jl#2005] opened 2022-09-20 15:54 UTC
When I was implementing a new variable set `Spin <: AbstractScalarSet` for $s \in \\\{-1, 1\\\}$ I kept running into calls to `MOIU._single_variable_flag`.

After correctly defining the JuMP extension interface things seemed to work but the problem persisted as I needed to perform `MOI` queries such as `MOI.get(model, MOI.ListOfConstraintIndices{VI, Spin}())`.

Here is a MWE:
```julia
# MWE imports:
using JuMP
const MOIU = MOI.Utilities

# actual lib code:
# ~*~ MOI ~*~ #
@doc raw"""
    Spin()

The set ``\left\lbrace{}{-1, 1}\right\rbrace{}``.
""" struct Spin <: MOI.AbstractScalarSet end

function MOIU._to_string(options::MOIU._PrintOptions, ::Spin)
    return string(MOIU._to_string(options, ∈), " {-1, 1}")
end

function MOIU._to_string(::MOIU._PrintOptions{MIME"text/latex"}, ::Spin)
    return raw"\in \left\lbrace{}{-1, 1}\right\rbrace{}"
end

# ~*~ JuMP ~*~ #
# Ref: https://jump.dev/JuMP.jl/stable/developers/extensions/#extend_variable_macro

struct SpinInfo
    info::JuMP.VariableInfo
end

function JuMP.build_variable(
    ::Function,
    info::JuMP.VariableInfo,
    ::Type{Spin};
    kwargs...
)
    return SpinInfo(info)
end

function JuMP.add_variable(
    model::JuMP.Model,
    info::SpinInfo,
    name::String,
)
    x = JuMP.add_variable(model, JuMP.ScalarVariable(info.info), name)

    JuMP.@constraint(model, x ∈ Spin())

    return x
end

JuMP.in_set_string(::MIME"text/plain", ::Spin) = "spin"
JuMP.in_set_string(::MIME"text/latex", ::Spin) = raw"\in \left\langle{}-1, 1\right\rangle{}}"

# MWE again:
m = MOIU.Model{Float64}()
MOI.get(m, MOI.ListOfConstraintIndices{MOI.VariableIndex, Spin}()) # Method Error: no method matching _single_variable_flag(::Type{Spin})
# `MOI.ConstraintIndex{MOI.VariableIndex, Spin}[]` is the expected return
```

A pirate fix for this was to define
```julia
MOIU._single_variable_flag(::Type{Spin}) = 0x0100 # last flag used was 0x0080
```

The polite fix was to ask if `MOI.supports(model, VI, Spin)` before asking for the possibly empty list.

I think that maybe other `MOI.get` methods involving constraints might fail as they reach `_single_variable_flag` too.

AFAIK, this whole flag system is only used to do basic comparison between variable types by calling `!iszero(mask & flag)` on them.
Is this still necessary to avoid type comparison `===`/inclusion `<:` or should we consider replacing this mechanism?

**Comment by blegat** [comment] 2022-09-20 19:05
The fix is ton add `S<:SUPPORTED_VARIABLE_SCALAR_SETS{T}` here
https://github.com/jump-dev/MathOptInterface.jl/blob/be1c8c3b30cc3a27aa50c285b9b38940716d47ca/src/Utilities/variables_container.jl#L381

**Comment by odow** [comment] 2022-09-22 17:37
Was this closed by #2007?

**Comment by pedromxavier** [comment] 2022-09-22 18:22
I'm not sure. The MWE above now results in:
```julia
ERROR: MethodError: no method matching get(::MathOptInterface.Utilities.VariablesContainer{Float64}, ::MathOptInterface.ListOfConstraintIndices{MathOptInterface.VariableIndex, Spin})
```
It still reaches `VariablesContainer` but now avoids the flag system.

**Comment by odow** [comment] 2022-09-22 22:27
The issue is really that `MOIU.Model{Float64}()` doesn't support `Spin`. I guess we need a generic fallback that checks support first.

**Closed** 2022-09-26 03:52 UTC
