### ISSUE TITLE
[FileFormats.LP] assertion error reading LP file

### ISSUE THREAD

**Issue by stumarcus314** [jump-dev/MathOptInterface.jl#2075] opened 2023-01-11 05:09 UTC
read_from_file throws an error when trying to read an LP file (min_max_overlap_Gen8.lp, which is 1.6 MB and is comprised of 33,885 lines), representing a MILP. SCIP on the NEOS Server is able to read and solve the LP file. The code below works fine for a very simple LP file (model2.lp).

The error is:
```julia
$ julia solve_LP.jl
ERROR: LoadError: AssertionError: token_types[offset] == _TOKEN_QUADRATIC_OFF_DIAG
Stacktrace:
[1] _get_term
@ ~/.julia/packages/MathOptInterface/o3YPB/src/FileFormats/LP/LP.jl:551 [inlined]
[2] _parse_function(f::MathOptInterface.ScalarAffineFunction{Float64}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, tokens::Vector{String})
@ MathOptInterface.FileFormats.LP ~/.julia/packages/MathOptInterface/o3YPB/src/FileFormats/LP/LP.jl:589
[3] _parse_section(#unused#::Val{:constraints}, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, cache::MathOptInterface.FileFormats.LP._ReadCache, line::SubString{String})
@ MathOptInterface.FileFormats.LP ~/.julia/packages/MathOptInterface/o3YPB/src/FileFormats/LP/LP.jl:705
[4] read!(io::IOStream, model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}})
@ MathOptInterface.FileFormats.LP ~/.julia/packages/MathOptInterface/o3YPB/src/FileFormats/LP/LP.jl:959
[5] #11
@ ~/.julia/packages/MathOptInterface/o3YPB/src/FileFormats/FileFormats.jl:121 [inlined]
[6] open(::MathOptInterface.FileFormats.var"#11#12"{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}}, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
@ Base ./io.jl:330
[7] open(::Function, ::String, ::String)
@ Base ./io.jl:328
[8] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.NoCompression)
@ MathOptInterface.FileFormats ~/.julia/packages/MathOptInterface/o3YPB/src/FileFormats/utils.jl:213
[9] compressed_open(f::Function, filename::String, mode::String, #unused#::MathOptInterface.FileFormats.AutomaticCompression)
@ MathOptInterface.FileFormats ~/.julia/packages/MathOptInterface/o3YPB/src/FileFormats/utils.jl:251
[10] read_from_file(model::MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ObjectiveContainer{Float64}, MathOptInterface.Utilities.VariablesContainer{Float64}, MathOptInterface.FileFormats.LP.ModelFunctionConstraints{Float64}}, filename::String)
@ MathOptInterface.FileFormats ~/.julia/packages/MathOptInterface/o3YPB/src/FileFormats/FileFormats.jl:120
[11] read_from_file(filename::String; format::MathOptInterface.FileFormats.FileFormat, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
@ JuMP ~/.julia/packages/JuMP/vuP7I/src/file_formats.jl:112
[12] read_from_file(filename::String)
@ JuMP ~/.julia/packages/JuMP/vuP7I/src/file_formats.jl:110
[13] top-level scope
@ ~/solve_LP.jl:4
in expression starting at /home/muck/solve_LP.jl:4
```

The code is below:

```Julia
using JuMP
using SCIP

m = read_from_file(“min_max_overlap_Gen8.lp”)
#m = read_from_file(“model2.lp”)
#m = read_from_file(“sample2.mps”)
set_optimizer(m,SCIP.Optimizer)
optimize!(m)
```

**Comment by odow** [comment] 2023-01-11 05:57
Can you upload the `min_max_overlap_Gen8.lp` file? I can't reproduce this without it.

**Comment by stumarcus314** [comment] 2023-01-11 17:20
Attached is the LP file.
[min_max_overlap_Gen8.zip](https://github.com/jump-dev/MathOptInterface.jl/files/10394567/min_max_overlap_Gen8.zip)

**Comment by odow** [comment] 2023-01-11 18:39
The reproducible example is:
```
Minimize
 x -1 y
End
```

The reader doesn't support `-1` without a sign token in between. I'll get this fixed.

**Comment by stumarcus314** [comment] 2023-01-11 20:39
If update my JuMP package (currently v1.6.0) in Julia, will this fix be reflected?

**Comment by odow** [comment] 2023-01-11 21:35
Update once https://github.com/JuliaRegistries/General/pull/75525 is merged. You should see MathOptInterface update from v1.11.2 to v1.11.3.

**Comment by stumarcus314** [comment] 2023-01-11 21:51
How do I check my version of MathOptInterface? I installed the JuMP package, but not the MathOptInterface package.

julia> using MathOptInterface
 │ Package MathOptInterface not found, but a package named MathOptInterface is available from a registry.
 │ Install package?
 │   (@v1.7) pkg> add MathOptInterface
 └ (y/n) [y]: n

**Comment by odow** [comment] 2023-01-11 21:59
You don't need to install MathOptInterface directly. Just run `] update`. 

You can check the version using `] status -m MathOptInterface`:

```julia
(moi) pkg> status
      Status `/private/tmp/moi/Project.toml`
  [4076af6c] JuMP v1.6.0

(moi) pkg> status -m MathOptInterface
      Status `/private/tmp/moi/Manifest.toml`
  [b8f27783] MathOptInterface v1.11.3
```

**Comment by stumarcus314** [comment] 2023-01-11 23:13
I was able to update to MathOptInterface v1.11.3. 

I converted the LP file to an MPS file using GLPK's glpsol. When I try to solve the LP file using JuMP, SCIP says the problem is infeasible. However, SCIP is able to solve the MPS file to optimality within JuMP. On the NEOS-Server, SCIP is able to solve both the LP and MPS files to optimality.

(@v1.7) pkg> update
    Updating registry at `~/.julia/registries/General.toml`
   Installed SnoopPrecompile ── v1.0.3
   Installed MathOptInterface ─ v1.11.3
  No Changes to `~/.julia/environments/v1.7/Project.toml`
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [b8f27783] ↑ MathOptInterface v1.11.2 ⇒ v1.11.3
  [66db9d55] ↑ SnoopPrecompile v1.0.1 ⇒ v1.0.3
Precompiling project...
  9 dependencies successfully precompiled in 47 seconds (65 already precompiled)

SCIP in JuMP does not solve the LP file properly:
$ julia solve_LP.jl
presolving:
(round 1, fast)       3276 del vars, 9788 del conss, 6 add conss, 3317 chg bounds, 7351 chg sides, 14289 chg coeffs, 0 upgd conss, 1 impls, 1428 clqs
presolving (2 rounds: 2 fast, 0 medium, 0 exhaustive):
 3283 deleted vars, 9789 deleted constraints, 6 added constraints, 3318 tightened bounds, 0 added holes, 7351 changed sides, 14289 changed coefficients
 1 implications, 1428 cliques
presolving detected infeasibility
Presolving Time: 0.04

SCIP Status        : problem is solved [infeasible]
Solving Time (sec) : 0.06
Solving Nodes      : 0
Primal Bound       : +1.00000000000000e+20 (0 solutions)
Dual Bound         : +1.00000000000000e+20
Gap                : 0.00 %

SCIP in JuMP solves the MPS file properly:
$ julia solve_LP.jl
presolving:
(round 1, fast)       290 del vars, 865 del conss, 6 add conss, 336 chg bounds, 10245 chg sides, 27577 chg coeffs, 0 upgd conss, 1 impls, 2912 clqs
(round 2, fast)       410 del vars, 1370 del conss, 12 add conss, 518 chg bounds, 14944 chg sides, 46273 chg coeffs, 0 upgd conss, 1 impls, 2852 clqs
(round 3, fast)       490 del vars, 1672 del conss, 16 add conss, 639 chg bounds, 16184 chg sides, 51161 chg coeffs, 0 upgd conss, 1 impls, 2812 clqs
(round 4, fast)       538 del vars, 1856 del conss, 17 add conss, 716 chg bounds, 17423 chg sides, 56065 chg coeffs, 0 upgd conss, 1 impls, 2788 clqs
(round 5, fast)       562 del vars, 1953 del conss, 17 add conss, 760 chg bounds, 19736 chg sides, 65281 chg coeffs, 0 upgd conss, 1 impls, 2776 clqs
(round 6, fast)       570 del vars, 1990 del conss, 18 add conss, 779 chg bounds, 20951 chg sides, 70121 chg coeffs, 0 upgd conss, 1 impls, 2772 clqs
   (0.1s) running MILP presolver
   (5.9s) MILP presolver (29 rounds): 10 aggregations, 1200 fixings, 54 bound changes
(round 7, medium)     1780 del vars, 1994 del conss, 19 add conss, 837 chg bounds, 20951 chg sides, 70121 chg coeffs, 0 upgd conss, 1 impls, 1960 clqs
(round 8, fast)       1780 del vars, 4790 del conss, 20 add conss, 837 chg bounds, 22319 chg sides, 73986 chg coeffs, 0 upgd conss, 1 impls, 1960 clqs
(round 9, exhaustive) 1780 del vars, 6514 del conss, 20 add conss, 837 chg bounds, 22666 chg sides, 73986 chg coeffs, 0 upgd conss, 1 impls, 1960 clqs
(round 10, exhaustive) 1780 del vars, 6514 del conss, 20 add conss, 837 chg bounds, 22666 chg sides, 73986 chg coeffs, 2078 upgd conss, 1 impls, 1960 clqs
(round 11, fast)       1780 del vars, 6514 del conss, 20 add conss, 837 chg bounds, 22680 chg sides, 74014 chg coeffs, 2078 upgd conss, 92 impls, 2026 clqs
(round 12, exhaustive) 1805 del vars, 6514 del conss, 20 add conss, 844 chg bounds, 22680 chg sides, 74014 chg coeffs, 2078 upgd conss, 1018 impls, 18633 clqs
(round 13, fast)       1805 del vars, 6551 del conss, 26 add conss, 852 chg bounds, 22703 chg sides, 74014 chg coeffs, 2078 upgd conss, 1018 impls, 18633 clqs
(round 14, exhaustive) 1805 del vars, 6571 del conss, 26 add conss, 852 chg bounds, 22703 chg sides, 74014 chg coeffs, 2078 upgd conss, 1018 impls, 18633 clqs
(round 15, exhaustive) 1805 del vars, 7017 del conss, 26 add conss, 852 chg bounds, 23159 chg sides, 74014 chg coeffs, 2078 upgd conss, 1018 impls, 18633 clqs
(round 16, exhaustive) 1805 del vars, 7017 del conss, 26 add conss, 852 chg bounds, 23159 chg sides, 74014 chg coeffs, 2095 upgd conss, 1018 impls, 18633 clqs
(round 17, medium)     1805 del vars, 7034 del conss, 26 add conss, 852 chg bounds, 23159 chg sides, 74014 chg coeffs, 2095 upgd conss, 1018 impls, 18633 clqs
(round 18, exhaustive) 1830 del vars, 7034 del conss, 26 add conss, 855 chg bounds, 23159 chg sides, 74014 chg coeffs, 2095 upgd conss, 1499 impls, 22578 clqs
(round 19, fast)       1830 del vars, 7084 del conss, 32 add conss, 863 chg bounds, 23184 chg sides, 74014 chg coeffs, 2095 upgd conss, 1499 impls, 22578 clqs
(round 20, exhaustive) 1830 del vars, 7100 del conss, 32 add conss, 863 chg bounds, 23184 chg sides, 74014 chg coeffs, 2095 upgd conss, 1499 impls, 22578 clqs
(round 21, exhaustive) 1830 del vars, 7100 del conss, 32 add conss, 863 chg bounds, 23184 chg sides, 74014 chg coeffs, 2107 upgd conss, 1499 impls, 22578 clqs
(round 22, medium)     1830 del vars, 7112 del conss, 32 add conss, 863 chg bounds, 23184 chg sides, 74014 chg coeffs, 2107 upgd conss, 1499 impls, 22578 clqs
   (10.8s) probing: 1000/4348 (23.0%) - 48 fixings, 2 aggregations, 184014 implications, 29 bound changes
   (11.2s) probing: 1130/4348 (26.0%) - 48 fixings, 2 aggregations, 203034 implications, 30 bound changes
   (11.2s) probing aborted: 1000/1000 successive useless probings
   (11.2s) symmetry computation started: requiring (bin +, int -, cont +), (fixed: bin -, int +, cont -)
   (11.2s) symmetry computation finished: 1 generators found (max: 1500, log10 of symmetry group size: 0.3)
presolving (23 rounds: 23 fast, 13 medium, 10 exhaustive):
 1830 deleted vars, 7112 deleted constraints, 33 added constraints, 883 tightened bounds, 0 added holes, 23184 changed sides, 74014 changed coefficients
 19440 implications, 90331 cliques
presolved problem has 4368 variables (4298 bin, 5 int, 65 impl, 0 cont) and 14468 constraints
    114 constraints of type <varbound>
   1958 constraints of type <setppc>
  12395 constraints of type <linear>
      1 constraints of type <orbitope>
transformed objective value is always integral (scale: 1)
Presolving Time: 11.23

 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl.
 11.9s|     1 |     0 |  6452 |     - |   136M |   0 |4368 |  14k|  14k|   0 |  0 |  18 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 13.2s|     1 |     0 | 12912 |     - |   137M |   0 |4368 |  14k|  14k|   0 |  0 |  18 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 13.6s|     1 |     0 | 15050 |     - |   141M |   0 |4368 |  14k|  14k|  42 |  1 |  18 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 13.7s|     1 |     0 | 15175 |     - |   143M |   0 |4368 |  14k|  14k|  51 |  2 |  19 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 14.0s|     1 |     0 | 15203 |     - |   144M |   0 |4368 |  14k|  14k|  58 |  3 |  21 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 14.3s|     1 |     0 | 15212 |     - |   146M |   0 |4368 |  14k|  14k|  62 |  4 |  21 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 14.5s|     1 |     0 | 15348 |     - |   148M |   0 |4368 |  14k|  14k|  68 |  5 |  21 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 14.8s|     1 |     0 | 15429 |     - |   149M |   0 |4368 |  14k|  14k|  72 |  6 |  21 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 14.9s|     1 |     0 | 15437 |     - |   151M |   0 |4368 |  14k|  14k|  75 |  7 |  21 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 15.0s|     1 |     0 | 15494 |     - |   153M |   0 |4368 |  14k|  14k|  77 |  8 |  23 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 15.5s|     1 |     0 | 15500 |     - |   154M |   0 |4368 |  14k|  14k|  79 |  9 |  23 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 15.7s|     1 |     0 | 15662 |     - |   157M |   0 |4368 |  14k|  14k|  83 | 10 |  23 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 15.8s|     1 |     0 | 15830 |     - |   158M |   0 |4368 |  14k|  14k|  86 | 11 |  23 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 15.9s|     1 |     0 | 15838 |     - |   159M |   0 |4368 |  14k|  14k|  89 | 12 |  23 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 16.0s|     1 |     0 | 15838 |     - |   160M |   0 |4368 |  14k|  14k|  89 | 12 |  23 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 time | node  | left  |LP iter|LP it/n|mem/heur|mdpt |vars |cons |rows |cuts |sepa|confs|strbr|  dualbound   | primalbound  |  gap   | compl.
 16.0s|     1 |     0 | 15844 |     - |   161M |   0 |4368 |  14k|  14k|  94 | 13 |  23 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 16.1s|     1 |     0 | 15851 |     - |   162M |   0 |4368 |  14k|  14k|  99 | 14 |  23 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 16.1s|     1 |     0 | 15858 |     - |   164M |   0 |4368 |  14k|  14k| 104 | 15 |  24 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 16.2s|     1 |     0 | 15867 |     - |   165M |   0 |4368 |  14k|  14k| 105 | 16 |  24 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 16.3s|     1 |     0 | 15872 |     - |   165M |   0 |4368 |  14k|  14k| 109 | 17 |  24 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 16.3s|     1 |     0 | 15874 |     - |   165M |   0 |4368 |  14k|  14k| 111 | 18 |  24 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 16.4s|     1 |     0 | 15876 |     - |   167M |   0 |4368 |  14k|  14k| 113 | 19 |  24 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 16.5s|     1 |     0 | 15884 |     - |   167M |   0 |4368 |  14k|  14k| 120 | 20 |  26 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 16.6s|     1 |     0 | 15886 |     - |   167M |   0 |4368 |  14k|  14k| 122 | 21 |  26 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 16.6s|     1 |     0 | 15887 |     - |   167M |   0 |4368 |  14k|  14k| 124 | 22 |  26 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 16.7s|     1 |     0 | 15888 |     - |   167M |   0 |4368 |  14k|  14k| 125 | 23 |  27 |   0 |-5.500000e+01 |      --      |    Inf | unknown
 17.4s|     1 |     2 | 16570 |     - |   168M |   0 |4368 |  14k|  14k| 125 | 23 |  30 |  20 |-5.500000e+01 |      --      |    Inf | unknown
*20.1s|    27 |    24 | 38532 | 870.9 |    LP  |   9 |4368 |  14k|  14k| 125 |  1 |  63 |  20 |-5.500000e+01 |-5.200000e+01 |   5.77%|   0.78%
 26.1s|   100 |    45 |100129 | 850.9 |   183M |  15 |4368 |  14k|  14k| 250 |  1 | 381 |  20 |-5.500000e+01 |-5.200000e+01 |   5.77%|  24.26%
 30.2s|   200 |    16 |163441 | 741.5 |   190M |  20 |4368 |  15k|  14k| 346 |  1 | 540 |  20 |-5.500000e+01 |-5.200000e+01 |   5.77%|  78.15%

SCIP Status        : problem is solved [optimal solution found]
Solving Time (sec) : 32.24
Solving Nodes      : 232
Primal Bound       : -5.20000000000000e+01 (1 solutions)
Dual Bound         : -5.20000000000000e+01
Gap                : 0.00 %

**Comment by stumarcus314** [comment] 2023-01-11 23:13
Attached are the LP an MPS files.
[input_files.zip](https://github.com/jump-dev/MathOptInterface.jl/files/10396648/input_files.zip)

**Comment by odow** [comment] 2023-01-11 23:46
I'll take a look. As a side note, why are you reading/writing LP files?

**Comment by stumarcus314** [comment] 2023-01-11 23:54
I create my model in MATLAB using the YALMIP toolbox, which is only able to write LP files. YALMIP does not write MPS files.

**Comment by odow** [comment] 2023-01-12 00:09
> I create my model in MATLAB using the YALMIP toolbox

Ah. The LP file format doesn't have a well-defined schema, and the file you're creating is non-standard: https://github.com/jump-dev/MathOptInterface.jl/pull/2078. 

> I create my model in MATLAB using the YALMIP toolbox

So why are you using JuMP? Why not build the entire model in JuMP? Or just use YALMIP for interacting with the solver?

**Comment by stumarcus314** [comment] 2023-01-12 00:16
At present, it's easier to build the model in YALMIP. YALMIP doesn't interface with HiGHS and interfaces with an old version of SCIP (v5.0.1) through the OPTI Toolbox (https://github.com/jonathancurrie/OPTI), which is no longer developed.

**Comment by odow** [comment] 2023-01-12 00:30
> At present, it's easier to build the model in YALMIP

What features of YALMIP make it easier? And why not use Cbc via YALMIP? That's free and interfaced by YALMIP.

Going YALMIP -> LP -> JuMP -> Solver seems like a lot of overhead and hassle.

**Comment by stumarcus314** [comment] 2023-01-12 00:40
YALMIP can build a model using many MATLAB constructs (like matrix operations), high level variable operators (such as min, nnz, and sort), and high level constraints (such as alldifferent). 
https://yalmip.github.io/allcommands

Cbc is inferior to HiGHS and SCIP. My MILPs are solved much more efficiently by HiGHS and SCIP compared to Cbc. In addition, like SCIP, YALMIP interfaces Cbc through the OPTI Toolbox, which is no longer developed. So YALMIP is stuck on Cbc v2.9.9.
https://yalmip.github.io/solver/cbc/

**Comment by stumarcus314** [comment] 2023-01-12 00:51
These MILP benchmarks support my claim that HiGHS and SCIP are more performant than Cbc.
http://plato.asu.edu/ftp/milp.html
http://plato.asu.edu/ftp/path.html
http://plato.asu.edu/ftp/infeas.html

**Comment by odow** [comment] 2023-01-12 00:57
> high level variable operators (such as min, nnz, and sort), and high level constraints (such as alldifferent).

Are you using these? I'd be interested to see your MATLAB code to see if there was an easy way to write it in JuMP. We also support matrix operators, etc. You can email me if you don't want it public: o.dowson@gmail.com

**Comment by stumarcus314** [comment] 2023-01-12 01:05
Yes, I am using those high level variable operators and constraints to build my model in YALMIP.

**Comment by odow** [comment] 2023-01-12 01:19
You can test the latest change with `import Pkg; Pkg.pkg"add MathOptInterface#master"`, then restart Julia.

**Closed** 2023-01-12 01:18 UTC
Labels: Type: Bug, Submodule: FileFormats

**Comment by stumarcus314** [comment] 2023-01-12 01:33
After following your instructions, JuMP is able to read and solve the LP file using SCIP and HiGHS as solvers.

julia> import Pkg; Pkg.pkg"add MathOptInterface#master"
     Cloning git-repo `https://github.com/jump-dev/MathOptInterface.jl.git`
    Updating git-repo `https://github.com/jump-dev/MathOptInterface.jl.git`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/.julia/environments/v1.7/Project.toml`
  [b8f27783] + MathOptInterface v1.11.3 `https://github.com/jump-dev/MathOptInterface.jl.git#master`
    Updating `~/.julia/environments/v1.7/Manifest.toml`
  [b8f27783] ~ MathOptInterface v1.11.3 ⇒ v1.11.3 `https://github.com/jump-dev/MathOptInterface.jl.git#master`
Precompiling project...
  5 dependencies successfully precompiled in 35 seconds (69 already precompiled)
