### ISSUE TITLE
add an NLP test with NaN returned from the callbacks

### ISSUE THREAD

**Issue by mlubin** [jump-dev/MathOptInterface.jl#470] opened 2018-08-15 23:35 UTC
Ref https://github.com/JuliaOpt/Ipopt.jl/pull/133

**Comment by shadiakiki1986** [comment] 2020-11-05 07:10
I'm trying to tackle this issue by writing tests for it in my forks of MOI and Ipopt. My results don't match with my expectations, so I have a few questions. This is very draft-ish with a lot of coding malpractices like function and variable names as well as unnecessary code from copy-paste.

1. Is my approach of implementing tests in MOI and calling them from Ipopt in line with how you're building the packages?
2. My first test `max_x_is_inf` is implemented in MOI [here](https://github.com/shadiakiki1986/MathOptInterface.jl/blob/sa/isue470_nlptest_nancallback/src/Test/nlp_nancallback.jl#L8), but it errors when called from Ipopt [here](https://github.com/shadiakiki1986/Ipopt.jl/blob/sa/nan_callbacks/test/MOI_nlp_nancallback.jl#L31) with `Attribute MathOptInterface.VariableName() is not supported by the model`. What I was aiming for with this test is to set up an optimization that goes to infinity and see if it starts popping up NaN's on the way to Inf. I ended up re-implementing this idea in my next test `nancb_test` (details below) but without the `MOIU.loadfromstring`, which I was hoping would work and be a very simple and compact implementation of tests for this issue. I think I'm missing something very obvious about the syntax of the string model here.
3. The next test `nancb_test` is defined in MOI [here](https://github.com/shadiakiki1986/MathOptInterface.jl/blob/sa/isue470_nlptest_nancallback/src/Test/nlp_nancallback.jl#L164) and called in Ipopt [here](https://github.com/shadiakiki1986/Ipopt.jl/blob/sa/nan_callbacks/test/MOI_nlp_nancallback.jl#L36). It is a simple `max x st x>=1`. It's mostly copied from the NLP HS071 test with modifications for the simpler model here. The termination status that ends up here is `MOI.NORM_LIMIT`, with primal status = `UNKNOWN_RESULT_STATUS`. The objective value comes out at 4.94, but I get it that whatever number here is invalid given the unknown status flag. I don't understand why it doesn't stop at something much larger, but maybe this has to do with some configurations for Ipopt that I missed.
4. The test `nancb_test2` is defined in MOI [here](https://github.com/shadiakiki1986/MathOptInterface.jl/blob/sa/isue470_nlptest_nancallback/src/Test/nlp_nancallback.jl#L307) and called in Ipopt [here](https://github.com/shadiakiki1986/Ipopt.jl/blob/sa/nan_callbacks/test/MOI_nlp_nancallback.jl#L41). It's the same idea as above, but the problem is `max 1/x st x>=-1`. The idea was to get an Inf while converging to 0. The termination status comes out as `MOI.ITERATION_LIMIT` (different than the previous test), with primal status as `MOI.UNKNOWN_RESULT_STATUS` as before. The objective value comes out at 0.06. I was expecting this to come out as much larger (closer to Inf).
5. The last test `nancb_test3` is defined in MOI [here](https://github.com/shadiakiki1986/MathOptInterface.jl/blob/sa/isue470_nlptest_nancallback/src/Test/nlp_nancallback.jl#L449) and called in Ipopt [here](https://github.com/shadiakiki1986/Ipopt.jl/blob/sa/nan_callbacks/test/MOI_nlp_nancallback.jl#L45). Here I bounded the variable to `0.01 <= x <= 1` and manually set NaNs in the gradient, jacobian, and hessian. Despite my bounding, I still get `INVALID_MODEL` (docs about it were added recently in the readme).
6. Thanks for getting this far. Am I in the right direction on this issue? I'd completely understand if it turns out that resolving this is just a 3-liner versus my 500 LOC.

**Closed** 2021-08-20 00:21 UTC
Labels: Submodule: Tests
