### ISSUE TITLE
Improve UnsupportedConstraint error message

### ISSUE THREAD

**Issue by blegat** [jump-dev/MathOptInterface.jl#1141] opened 2020-08-06 08:53 UTC
See https://github.com/jump-dev/KNITRO.jl/issues/167#issuecomment-669798842

**Comment by odow** [comment] 2020-12-14 06:12
This was caused by KNITRO incorrectly declaring that it supported Quadratic-in-Interval constraints: 
https://github.com/jump-dev/KNITRO.jl/blob/6fbee14d2e2417e81da93323abff92339a4cb7dd/src/MOI_wrapper/constraints.jl#L17

The current error message seems okay:
```Julia
model = direct_model(Gurobi.Optimizer())
@variable(model, x)
@constraint(model, 0 <= x <= 1)

# Yields

ERROR: Constraints of type MathOptInterface.ScalarAffineFunction{Float64}-in-MathOptInterface.Interval{Float64} are not supported by the solver.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] moi_add_constraint(::Gurobi.Optimizer, ::MathOptInterface.ScalarAffineFunction{Float64}, ::MathOptInterface.Interval{Float64}) at /Users/oscar/.julia/packages/JuMP/qhoVb/src/constraints.jl:394
 [3] add_constraint(::Model, ::ScalarConstraint{GenericAffExpr{Float64,VariableRef},MathOptInterface.Interval{Float64}}, ::String) at /Users/oscar/.julia/packages/JuMP/qhoVb/src/constraints.jl:408
 [4] top-level scope at /Users/oscar/.julia/packages/JuMP/qhoVb/src/macros.jl:441
 [5] top-level scope at REPL[7]:1
```

Although:
```Julia
model = Model(Gurobi.Optimizer)
@variable(model, x[1:2, 1:2], PSD)
optimize!(model)

# Yields

ERROR: MathOptInterface.UnsupportedConstraint{MathOptInterface.VectorOfVariables,MathOptInterface.PositiveSemidefiniteConeTriangle}: `MathOptInterface.VectorOfVariables`-in-`MathOptInterface.PositiveSemidefiniteConeTriangle` constraint is not supported by the model.
Stacktrace:
 [1] bridge_type(::MathOptInterface.Bridges.LazyBridgeOptimizer{Gurobi.Optimizer}, ::Type{MathOptInterface.PositiveSemidefiniteConeTriangle}) at /Users/oscar/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/lazy_bridge_optimizer.jl:312
 [2] concrete_bridge_type at /Users/oscar/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/Variable/bridge.jl:183 [inlined]
 [3] add_constrained_variables at /Users/oscar/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:1229 [inlined]
 [4] copy_vector_of_variables(::MathOptInterface.Bridges.LazyBridgeOptimizer{Gurobi.Optimizer}, ::MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}, ::MathOptInterface.Utilities.IndexMap, ::Type{MathOptInterface.PositiveSemidefiniteConeTriangle}, ::typeof(MathOptInterface.add_constrained_variables)) at /Users/oscar/.julia/packages/MathOptInterface/ZJFKw/src/Utilities/copy.jl:220
 [5] try_constrain_variables_on_creation(::MathOptInterface.Bridges.LazyBridgeOptimizer{Gurobi.Optimizer}, ::MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}, ::MathOptInterface.Utilities.IndexMap, ::Function, ::Function) at /Users/oscar/.julia/packages/MathOptInterface/ZJFKw/src/Utilities/copy.jl:408
 [6] default_copy_to(::MathOptInterface.Bridges.LazyBridgeOptimizer{Gurobi.Optimizer}, ::MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}, ::Bool, ::Nothing) at /Users/oscar/.julia/packages/MathOptInterface/ZJFKw/src/Utilities/copy.jl:459
 [7] #automatic_copy_to#137 at /Users/oscar/.julia/packages/MathOptInterface/ZJFKw/src/Utilities/copy.jl:21 [inlined]
 [8] #copy_to#3 at /Users/oscar/.julia/packages/MathOptInterface/ZJFKw/src/Bridges/bridge_optimizer.jl:293 [inlined]
 [9] attach_optimizer(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at /Users/oscar/.julia/packages/MathOptInterface/ZJFKw/src/Utilities/cachingoptimizer.jl:150
 [10] optimize!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at /Users/oscar/.julia/packages/MathOptInterface/ZJFKw/src/Utilities/cachingoptimizer.jl:211
 [11] optimize!(::Model, ::Nothing; bridge_constraints::Bool, ignore_optimize_hook::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/oscar/.julia/packages/JuMP/qhoVb/src/optimizer_interface.jl:130
 [12] optimize! at /Users/oscar/.julia/packages/JuMP/qhoVb/src/optimizer_interface.jl:106 [inlined] (repeats 2 times)
 [13] top-level scope at REPL[11]:1
```

**Comment by odow** [comment] 2021-07-14 23:30
Closing because this is fine for now. The original issue was caused by an incorrect implementation in KNITRO.jl.

**Closed by odow** 2021-07-14 23:30 UTC
