### ISSUE TITLE
Problems with Convex.jl , MathOptInterface.jl and COSMO.jl

### ISSUE THREAD

**Issue by dnaurch** [jump-dev/MathOptInterface.jl#1801] opened 2022-04-08 22:31 UTC
I have tried to solve this problem but I could not find any solution anywhere after a lot of Google searches.

I am trying to do a LASSO model optimization with below code as global_LASSO.jl

```julia
##### optimization procedure for group LASSO
# # Use SCS solver or COSMO solver

using Random, LinearAlgebra, SparseArrays, Convex, COSMO

### generate evenly spaced lambda
function evenly_spaced(a, b, n)
    h = (b-a)/(n-1)
    collect(a:h:b)
end

function groupLASSO(y, X, vgrp)
# Solver can either be COSMO or SCS

#   if Solver == "SCS"
#	solver = () -> SCS.Optimizer()
#   else 
#   	solver = () -> COSMO.Optimizer()
#   end

# solve at a grid of λ
#λgrid = 0.1:0.005:0.5

#λgrid = evenly_spaced(1000.0, 0.01, 10)

λgrid = 0.01

β̂pathgrp = zeros(length(λgrid), size(X, 2)) # each row is β̂ at a λ
β̂classo = Variable(size(X, 2))

@time for i in 1:size(λgrid,1)
    λ = λgrid[i]
    # loss
    obj = 0.5sumsquares(y - X * β̂classo)
    # group lasso penalty term
    for j in unique(vgrp)
        indx = findall(x->x==j, vgrp)
        βj = β̂classo[indx]
        obj = obj + λ * norm(βj)
    end
    problem = minimize(obj)
    # constraint
    problem.constraints += sum(β̂classo) == 0 # constraint
    solve!(problem, () -> COSMO.Optimizer(verbose = true))
    β̂pathgrp[i, :] = β̂classo.value
end

m11 = Dict(
       :beta_lambdas => β̂pathgrp)

return(m11)

end

```

My data is large with X (2000 x 300000) matrix and y 2000 vector.

I solve via JuliaCall library in R as follows:

```
script = "/home/group_LASSO.jl"
julia_assign("script", script)
julia_source(script)

julia_assign("X", X);
julia_assign("y", y);
julia_assign("vgrp", v.grp);

Solver = "COSMO"
julia_assign("Solver", Solver);

m1 <- julia_eval("mm = groupLASSO(y, X, vgrp)")
```

I get the error:

```
Error: Error happens in Julia.
MethodError: no method matching _pass_attributes(::Optimizer{Float64}, ::MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}, ::MathOptInterface.Utilities.IndexMap, ::Array{MathOptInterface.AbstractModelAttribute,1}, ::Tuple{}, ::Tuple{}, ::Tuple{}, ::typeof(MathOptInterface.Utilities.load))
Closest candidates are:
  _pass_attributes(::MathOptInterface.ModelLike, ::MathOptInterface.ModelLike, !Matched::Bool, !Matched::MathOptInterface.Utilities.IndexMap, ::Any, ::Any, ::Any, ::Any) at /home/uche/.julia/packages/MathOptInterface/A2UPd/src/Utilities/copy.jl:131
  _pass_attributes(::MathOptInterface.ModelLike, ::MathOptInterface.ModelLike, !Matched::Bool, !Matched::MathOptInterface.Utilities.IndexMap, ::Any, ::Any, ::Any, ::Any, !Matched::Function) at /home/uche/.julia/packages/MathOptInterface/A2UPd/src/Utilities/copy.jl:131
Stacktrace:
 [1] pass_attributes!(::Optimizer{Float64}, ::MathOptInterface.Utilities.UniversalFal
```

And if I change this `() -> COSMO.Optimizer(verbose = true)` in the group_LASSO.jl code to `COSMO.Optimizer(verbose = true)`, I still get errors:

```
Error: Error happens in Julia.
MethodError: no method matching solve!(::Problem{Float64}, ::Type{Optimizer})
Closest candidates are:
  solve!(::Problem{T}, !Matched::MathOptInterface.ModelLike; check_vexity, verbose, warmstart) where T at /home/uche/.julia/packages/Convex/pjPNw/src/solution.jl:199
Stacktrace:
 [1] LassoEN(::Array{Float64,2}, ::Array{Float64,2}, ::Float64, ::Array{Float64,1}, ::Int64) at /home/software/rnd/Harmonia/Scripts/group_ML.jl:61
 [2] LassoEN(::Array{Float64,2}, ::Array{Float64,2}, ::Float64, ::Array{Float64,1}) at /home/software/rnd/Harmonia/Scripts/group_ML.jl:21
 [3] top-level scope at none:0
 [4] eval(::Module, ::Any) at ./boot.jl:319
 [5] eval_string(::String) at /usr/local/lib/R/site-library/JuliaCall/julia/setup.jl:203
 [6] docall(::Ptr{Nothing}) at /usr/local/lib/R/site-library/JuliaCall/julia/setup.jl:176
```

Please it would be nice to get someone help. 

Thank you so much.

UGO.

**Comment by odow** [comment] 2022-04-09 03:09
Are you using the latest versions of every package? What is `import Pkg; Pkg.status()`?

I can't reproduce this:
```Julia
julia> using Random, LinearAlgebra, SparseArrays, Convex, COSMO

julia> function evenly_spaced(a, b, n)
           h = (b-a)/(n-1)
           collect(a:h:b)
       end
evenly_spaced (generic function with 1 method)

julia> function groupLASSO()
           y = rand(2)
           X = rand(2, 300)
           vgrp = [1, 2, 3]
           λgrid = 0.01
           β̂pathgrp = zeros(length(λgrid), size(X, 2)) # each row is β̂ at a λ
           β̂classo = Variable(size(X, 2))
           @time for i in 1:size(λgrid,1)
               λ = λgrid[i]
               # loss
               obj = 0.5sumsquares(y - X * β̂classo)
               # group lasso penalty term
               for j in unique(vgrp)
                   indx = findall(x->x==j, vgrp)
                   βj = β̂classo[indx]
                   obj = obj + λ * norm(βj)
               end
               problem = minimize(obj)
               # constraint
               problem.constraints += sum(β̂classo) == 0 # constraint
               solve!(problem, () -> COSMO.Optimizer(verbose = true))
               β̂pathgrp[i, :] = β̂classo.value
           end
           m11 = Dict(:beta_lambdas => β̂pathgrp)
           return m11
       end
groupLASSO (generic function with 1 method)

julia> groupLASSO()
------------------------------------------------------------------
          COSMO v0.8.5 - A Quadratic Objective Conic Solver
                         Michael Garstka
                University of Oxford, 2017 - 2022
------------------------------------------------------------------

Problem:  x ∈ R^{306},
          constraints: A ∈ R^{15x306} (915 nnz),
          matrix size to factor: 321x321,
          Floating-point precision: Float64
Sets:     SecondOrderCone of dim: 3
          SecondOrderCone of dim: 3
          ZeroSet of dim: 2
          SecondOrderCone of dim: 2
          SecondOrderCone of dim: 2
          ... and 2 more
Settings: ϵ_abs = 1.0e-05, ϵ_rel = 1.0e-05,
          ϵ_prim_inf = 1.0e-04, ϵ_dual_inf = 1.0e-04,
          ρ = 0.1, σ = 1e-06, α = 1.6,
          max_iter = 5000,
          scaling iter = 10 (on),
          check termination every 25 iter,
          check infeasibility every 40 iter,
          KKT system solver: QDLDL
Acc:      Anderson Type2{QRDecomp},
          Memory size = 15, RestartedMemory,	
          Safeguarded: true, tol: 2.0
Setup Time: 886.8ms

Iter:	Objective:	Primal Res:	Dual Res:	Rho:
1	-2.4770e+00	5.5123e+00	6.0000e-01	1.0000e-01
25	-2.3283e-10	2.3283e-10	1.2168e-20	1.0000e-01

------------------------------------------------------------------
>>> Results
Status: Solved
Iterations: 25
Optimal objective: -2.328e-10
Runtime: 2.73s (2730.17ms)

 11.576117 seconds (19.48 M allocations: 1.118 GiB, 2.89% gc time, 38.53% compilation time)
Dict{Symbol, Matrix{Float64}} with 1 entry:
  :beta_lambdas => [1.72268e-20 -9.99743e-21 … 0.0080186 -0.00740576]
```

**Comment by dnaurch** [comment] 2022-04-09 03:58
Here are the package versions I'm using:

```
julia> import Pkg; Pkg.status()
    Status `~/.julia/environments/v1.0/Project.toml`
  [1e616198] COSMO v0.8.2
  [f65535da] Convex v0.14.18
  [55d2b088] MUMPS v1.0.0 #master (https://github.com/JuliaSmoothOptimizers/MUMPS.jl.git)
  [b8f27783] MathOptInterface v0.9.22
  [d8a4904e] MutableArithmetics v0.2.22
  [86f7a689] NamedArrays v0.9.6
  [429524aa] Optim v0.22.0
  [6f49c342] RCall v0.13.11
  [e88e6eb3] Zygote v0.4.22
  [37e2e46d] LinearAlgebra 
  [2f01184e] SparseArrays 
  [10745b16] Statistics 
```
I am still running Julia Version 1.0.5 (2019-09-09) because it used to be the latest LTS version until I checked now and a new LTS was uploaded in March 28.

Thanks.

UGO.

**Comment by odow** [comment] 2022-04-09 04:09
Please update to the new Julia LTS version 1.6. It's much faster, greatly reduced time-to-first-x latency, and has a bunch of great new features. JuMP and MathOptInterface have been updated to require at least Julia 1.6, and we'll continue to support 1.6 for as long as it is the LTS. Updating to Julia 1.6 will also let you update to MathOptInterface v1.0, which will provide long-term stability.

Since I can't reproduce, I assume that I fixed this bug at some point, but let me know if you still have problems after updating.

**Comment by dnaurch** [comment] 2022-04-12 00:10
This works very well now. Thank you.

**Comment by odow** [comment] 2022-04-12 00:46
Great! Can I close this issue then? If you have future questions, please post on the community forum: https://discourse.julialang.org/c/domain/opt/13.

**Closed** 2022-04-12 13:37 UTC
Labels: Type: Question
